### PR TITLE
Fixes compilation error for Java 8

### PR DESCRIPTION
**Pull request by maddymanu**
## What was changed
Hi Guys!

I recently started playing with temporal, and I found this small issue while running the app on an older version of java. 
I didn't see a minimum version in the `build.gradle` so I assumed it's supposed to be working. 

Lemme know if I can add anything to PR!

1. Closes 
None

2. How was this tested:
Manually, compile using `./gradlew build`

3. Any docs updates needed?
None

image

### CODE REVIEW

**Comment by maddymanu** [comment]
@flossypurse @Spikhalskiy tagging you :) 
Lemme know if this helps!

**Comment by flossypurse** [comment]
Hey @maddymanu ! Thanks for doing this.
This app was made using using Java SE 14.0.1.

@tsurdilo - off the top of your head, is this change compatible with all versions?
Whats the minimum Java version we are supporting?

**Review by Spikhalskiy — APPROVED** [review]

**Comment by Spikhalskiy** [comment]
@flossypurse No harm in merging this. For JavaSDK our minimum language level is 8

**Comment by maddymanu** [comment]
Oh awesome @flossypurse @Spikhalskiy !
Thanks for the reviews.

One of you might need to merge, needs write access 😅

**Comment by flossypurse** [comment]
> @flossypurse No harm in merging this. For JavaSDK our minimum language level is 8

Hey thanks @Spikhalskiy!

**Pull request merged**
